phrase_list = [

#main characters
'omori',
'sunny',
'basil',
'kel',
'aubrey',
'hero',
'mari',

#other characters
'abbi', 'absent', 'actualmole', 'adonus', 'albacore', 'alextheesteemed', 'aliana', 'allamericanguy', 'allamericanmom', 'amelia', 'andrew', 'andy', 'angel', 'appleguy', 'applefly', 'artichoke', 'artist', 'aught',
'babo', 'bafino', 'bangs', 'barbarcoa', 'basketcase', 'beardghost', 'batzy', 'beautifulmole', 'berly', 'bigmolio', 'bigpocket', 'bigyellowcat','birdmole', 'biscuit', 'blank', 'blookie', 'bluehairedgirl', 'bluebird', 'bluecloud', 'bluegirl', 'bones', 'boss', 'bossmanhero', 'boxmole', 'branchcoral', 'breezy', 'brett', 'brianthedistinguished', 'brick', 'brooke', 'brothermole', 'brownhairylady', 'brows', 'budgirl', 'bun', 'burpmo', 'burro', 'butler', 'butlermole',
'candlebunny', 'candlie', 'canopy', 'captainspaceboy', 'caroltheillustrious', 'castella', 'cat', 'catpyramid', 'cesar', 'chad', 'charlene', 'checkersguy', 'chefmole', 'chelle', 'childonstilts', 'chow', 'cinder', 'cipher', 'citrus', 'cityslicker', 'clumsyguy', 'coffeemachine', 'colonymole', 'colorfulgirl', 'constructionmole', 'contestant', 'conveyorbot', 'cowblin', 'crab', 'creepyguy', 'croissant', 'crow', 'crusherblast', 'cutegirl',
'daddylonglegs', 'daisy', 'dancingmole', 'darville', 'dealerjash', 'decay', 'deerhead', 'demi', 'dino', 'divingman', 'donutgrandma', 'donuthole', 'doublemole', 'doughie', 'dowon', 'drew', 'duckiejr', 'duncemole',
'eleanor', 'empty', 'ems', 'energeticboy', 'experiment',
'faceless', 'fallmole', 'familiardoll', 'familymole', 'farmerjim', 'fashionablemom', 'ferris', 'fiesta', 'fishboy', 'fisherbear', 'fixitguy', 'frank', 'fred', 'frog', 'fucschia',
'gallipot', 'gardenermole', 'gascon', 'gasper', 'gatorguy', 'ghian', 'ghost', 'gibsthestationarymusician', 'glassesboy', 'glassesghost', 'glassesman', 'gluten', 'gonzo', 'gooddog', 'gooman', 'goosey', 'goylethecrab', 'gruffguy', 'grunty', 'guave', 'guestlistmole', 'guitarguy', 'gumbo',
'happy', 'hayes', 'headphoneskid', 'heather', 'hector', 'helenthecalamitous', 'hellmari', 'herosaurus', 'hitchhiker', 'hoagie', 'hoffy', 'holloy', 'honeydew', 'hotdiggitydog', 'hotdogguy', 'humphrey',
'impressivestatue', 'intimidatinggirl', 'izzy',
'jshroom', 'james', 'jash', 'jelly', 'jerko', 'jetsetter', 'jock', 'jockjams', 'jogen', 'jojo', 'jokerjash', 'jorge', 'julia', 'jussie',
'keeperofthecastle', 'keymagnet', 'kim', 'kitekid', 'krispy',
'lamb', 'laramie', 'largeface', 'leafie', 'lemonjash', 'littleone', 'loam', 'lonemole', 'longsnout', 'loomy', 'loquaciouscat', 'lucy', 'luke', 'lulu',
'maestro', 'maidmole', 'mailbox', 'marina', 'mayormole', 'meatman', 'medusa', 'megaphone', 'meido', 'messyhairman', 'mewo', 'miggie', 'mikal', 'mimi', 'mina', 'mincy', 'minus', 'mira', 'misscandice', 'moleontherun', 'molly', 'mooncake', 'morgan', 'mott', 'mountain', 'mrbaker', 'mrbird', 'mrduckie', 'mrjawsum', 'mroutback', 'mrparrot', 'mrpenguin', 'mrscarebro', 'mrscarecrow', 'mrscaethrow', 'mrseagull', 'mrsbaker', 'mrsduckie', 'mrsflamingo', 'mrsparrot', 'mush', 'musicalclam', 'mutanheart', 'mute',
'nathan', 'neb', 'nereene', 'newcolonymole', 'nose', 'nova', 'null',
'obaaa', 'oldbeardy', 'oldhobo', 'oldlady', 'oldmanwithglasses', 'omoli', 'operatorhumphrey', 'oragnejoe', 'orangecat', 'orangeguy', 'orangejoe', 'othertwin', 'othermartlady', 'owangee',
'pigtailslady', 'palmie', 'pam', 'papachip', 'parsnip', 'partyjash', 'parvenu', 'peanut', 'peeve', 'pellet', 'pencilman', 'perfectheart', 'pessi', 'pharmacist', 'pillowhider', 'pinataguy', 'pinkmirror', 'pinkmole', 'pinkbeard', 'pizzaman', 'pluto', 'po', 'polly', 'ponytailgirl', 'ponytaillady', 'popcorngirl', 'porinu', 'preacher', 'prettyboy', 'princessghost', 'prisonermole', 'professional', 'propellerghost',
'quaspy',
'rai', 'rarestbear', 'receptionisthumphrey', 'recyclepath', 'recycultist', 'redhands', 'redsmile', 'redglasseslady', 'rell', 'ren', 'renbi', 'reuben', 'ricoliravioli', 'rita', 'roamincow', 'roboheart', 'rococo', 'rosa', 'russell',
'sadie', 'sally', 'schoolprincipal', 'scott', 'scribble', 'scuba', 'seacow', 'sereno', 'shadowdog', 'shamboo', 'sharkpickle', 'sharleen', 'shawn', 'shopkeep', 'shorthairgirl', 'silker', 'simpleroach', 'sirmaximusiv', 'skele', 'skinnyboy', 'skullcrusher', 'sleepymole', 'slimegirls', 'smallgirl', 'smaartlookingboy', 'smellyhobo', 'smol', 'smugglerjash', 'snake', 'snaley', 'snoconejash', 'snowglobe', 'snug', 'soysauce', 'spaceexhusband', 'spacepiratechief', 'spacepirates', 'spaghetti', 'spellingbee', 'spidercat', 'sportmole', 'sproutmole', 'sproutmolemike', 'square', 'strangeman', 'stranger', 'studentmole', 'sully', 'summermole', 'sunhatghost', 'sweetheart', 'swethort', 'sydney',
'tako', 'tapioca', 'tater', 'taxidriver', 'teachermole', 'teacupspirit', 'theearth', 'thehooligans', 'themaverick', 'thickeyebrows', 'thisguy', 'tiffanydarling', 'tofuconconnasisseur', 'tofujash', 'tollgator', 'tollsnake', 'tophatghost', 'touchdown', 'trainstationjash', 'treble', 'trevor', 'tunacan', 'turmoil', 'tvgirl', 'twin',
'unbreadtwins', 'uni', 'urchin',
'van', 'vance', 'veggiekids', 'victor', 'vitruosomole', 'void',
'wardenmole', 'weecactus', 'weepingwillow', 'whatever', 'whizzywhitney', 'wily', 'wintermole', 'wisehumphrey', 'wiserock', 'wolf', 'wollie', 'wrinklyforehead',
'yellow', 'yelloowbungranny', 'youngshroom',
'zarf',
    

#other
'my' 'time',
'final' 'duet',
'good' 'morning',
'toast',
'something',

#locations
'white' 'space',
'black' 'space',
'head''space',
'red space',
'faraway''town',
'neighbors' 'room',
'vast' 'forest',
'otherworld',
'junkyard',
'orange' 'oasis',
'rain' 'town',
'pyrefly' 'forest',
'sprout' 'mole' 'village',
'sweethearts' 'castle',
'north' 'lake',
'last' 'resort',
'ghost' 'party',
'deep' 'well',
'deeper' 'well',
'humphrey',
'snowglobe' 'mountain',
'the' 'abyss',
'forest''playground',
'basils''house',
'pinwheel''forest',
'train''station',
'train',
'space''boyfriends''house',
'duckies''house',
'smols''house',
'pessis''house',
'tv''girls''house',
'frozen''lake',
'cattail''field',
'sprout''mole''colony',
'dinos''dig',
'breaven',
'donut''house',
'rells''house',
'palmies''house',
'orange''joes''house',
'lost''forest',
'the''dungeon',
'the''royal''chambers',
'the''royal''gallery',
'the''royal''library',
'the''royal''theater',
'the''royal''kitchen',
'the''royal''ballroom',
'lost''library',
'club''sandwich',
'mustard''sub',
'boss''rush',
'boring''room',
'neighbors''bedroom',
'northwest''road',
'northeast''road',
'southwest''road',
'southeast''road',
'faraway''park',
'hangout''spot',
'faraway''plaza',
'pain''area',
'disco''area',
'scribble''area',
'town''area',
'backyard''area',
'punishment''area',
'watermelon''area',
'beach''area',
'spider''area',
'rain''area',
'faceless''area',
'treehouse''area',
'fishbowl''area',
'raft''area',
'mirror''area',
'bed''area',
'reef''area',
'neighbor''area',
'church''of''something',
'lost''forest',
'the''docks',
'weathervane''area',
'cloud''walkway',
'developer''room',
'red''maze',
'maris''house',
'black''playground',
'red''room',
]